addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.4")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.5.2-RC1")
// addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.3.1")
